apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault_service:8200"
    - name: skipVerify
      value: true
    - name: vaultTokenMountPath # Required. Path to token file.
      value: "/vault/token"
    - name: vaultKVPrefix
      value: dapr
